# Generated by Django 5.1.4 on 2025-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalchoice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchoice',
            name='poll',
        ),
        migrations.AddField(
            model_name='historicalpoll',
            name='published',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='poll',
            name='published',
            field=models.BooleanField(default='False'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='HistoricalChoice',
        ),
    ]
